about:
    home: http://iraf.noao.edu/
    license: "Use at your own risk"
    summary: UCSCLRIS package for IRAF
build:
    binary_relocation: False
    number: '1'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.ucsclris
    version: "2013_01_02"
source:
    fn: ucsclris-src-2013-01-02.tar.gz
    url: http://astroconda-source:4440/ucsclris-src-2013-01-02.tar.gz
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    run:
    - iraf !=2.16.1,>=2.16.UR
    - iraf.stsdas  # used only by prep.qmask_plot

