{% set version = '1.0.27' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

package:
    name: gemini_obs_db
    version: {{ version }}
source:
    git_url: git@github.com:GeminiDRSoftware/GeminiObsDB.git
    git_tag: {{ tag }}
build:
    number: {{ number }}
    noarch: python
    script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    license_file: LICENSE
    summary: DB-backed classes to parse Gemini FITS metadata into various tables
requirements:
    build:
    - python >=3.7
    - pip
    - setuptools
    run:
    - python >=3.7
    - astropy >=4.3
    - dragons >=3.1.0
    - numpy >=1.17
    - python-dateutil >=2.5.3
    - sqlalchemy >=1.3,<2.0.0a0  # code not yet updated for new v2 API

