about:
    home: http://iraf.noao.edu/
    license: IRAF MIT/X11 variant, US government notice
    summary: CIRRED package for IRAF
build:
    binary_relocation: False
    number: '2'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.cirred
    version: "2007_12_13"
source:
    fn: cirred-2007-12-13.tgz
    url: http://astroconda-source:4440/cirred-2007-12-13.tgz
    patches:
    - ac.iraf.cirred.patch
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    run:
    - iraf !=2.16.1,>=2.16.UR
    - iraf.stsdas
