about:
    home: http://www.stsci.edu/institute/software_hardware/stsdas
    license: US government notice (and third-party licenses)
    summary: STScI TABLES package for IRAF
build:
    binary_relocation: False
    number: '0'
    # These must be copied from astroconda-iraf-helpers, as conda unhelpfully
    # disallows the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.tables
    version: "3.18"
source:
    # You must upload your ssh key to github to check out this private repo:
    git_url: git@github.com:spacetelescope/stsdas.git
    git_tag: 3.18
    patches:
    - ac.iraf.stsci.patch
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    run:
    - iraf !=2.16.1,>=2.16.UR  # (must ensure correct run-time "iraf" version)

