about:
    home: http://iraf.noao.edu/
    license: IRAF MIT/X11 variant, STSDAS US government notice
    summary: FINDER package for IRAF
build:
    binary_relocation: False
    number: '2'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.finder
    version: "2.2"
source:
    fn: finder-src-2.2.tar.gz
    url: http://astroconda-source:4440/finder-src-2.2.tar.gz
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    - iraf.tables
    run:
    - iraf !=2.16.1,>=2.16.UR
    - iraf.tables

