about:
    home: http://iraf.noao.edu/
    license: IRAF MIT/X11 variant
    summary: MSCDB package for IRAF
build:
    binary_relocation: False
    number: '2'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.mscdb
    version: "2011_02_28"
source:
    fn: mscdb-universal-2011-02-28.tar.gz
    url: http://astroconda-source:4440/mscdb-universal-2011-02-28.tar.gz
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    run:
    - iraf !=2.16.1,>=2.16.UR

