about:
    home: http://iraf.noao.edu/
    license: IRAF MIT/X11 variant (from SAO)
    summary: XRAY package for IRAF
build:
    binary_relocation: False
    number: '2'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.xray
    version: "2.5.y2k"
source:
    fn: xray_src_2.5.y2k.tar.gz
    url: http://astroconda-source:4440/xray_src_2.5.y2k.tar.gz
    patches:
    - ac.iraf.xray.patch
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    - iraf.tables
    run:
    - iraf !=2.16.1,>=2.16.UR
    - iraf.tables
    # The ctio package is also used by xapropos but we're building apropos
    # databases for the stsdas version instead.

