about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: Fee-free redistribution only (& 3rd-party non-commercial licenses)
    license_file: COPYRIGHT
    summary: Gemini IRAF package
build:
    binary_relocation: False
    number: '1'
    # These must be copied from astroconda-iraf-helpers, as conda unhelpfully
    # disallows the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.gemini
    version: "1.14"
source:
    fn: gemini_v114.tar.gz
    url: http://astroconda-source:4440/gemini_v114.tar.gz
    #patches:
    #- ac.iraf.gemini.patch
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR  # (build shouldn't depend on PyRAF or X11IRAF)
    - iraf.tables
    - iraf.stsdas
    - iraf.fitsutil
    run:
    - iraf !=2.16.1,>=2.16.UR  # (must ensure correct run-time "iraf" version)
    - iraf.tables
    - iraf.stsdas
    - iraf.fitsutil

