about:
    home: https://github.com/KeplerGO/PyKE/
    license: US government notice, BSD, attribution requirement
    summary: A suite of Python/PyRAF tools to analyze Kepler data
build:
    binary_relocation: False
    number: '1'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: pyraf.kepler
    version: "2.6.3"
source:
    fn: v2.6.3.tar.gz
    url: https://github.com/KeplerGO/PyKE/archive/v2.6.3.tar.gz
requirements:
    build:
    - python
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    run:
    - python
    - iraf !=2.16.1,>=2.16.UR
    - pyraf
    - astropy
    - matplotlib
    - numpy
    - scipy
    - mdp