about:
    home: http://iraf.noao.edu/
    license: IRAF MIT/X11 variant
    summary: XDIMSUM package for IRAF
build:
    binary_relocation: False
    number: '2'
    # These must be copied from astroconda-iraf-helpers, since conda disallows
    # the post-install step from depending on other packages:
    always_include_files:
    - bin/ac_config_iraf_pkg
    - bin/ac_update_extern_pkg
package:
    name: iraf.xdimsum
    version: "2010_11_18"
source:
    fn: xdimsum-src-2010-11-18.tar.gz
    url: http://astroconda-source:4440/xdimsum-src-2010-11-18.tar.gz
requirements:
    build:
    - astroconda-iraf-helpers
    - iraf !=2.16.1,>=2.16.UR
    run:
    - iraf !=2.16.1,>=2.16.UR
    # One task also uses STSDAS but it lives in the "obsolete" dir, so don't
    # pull in all of STSDAS just for that (unless user installs it manually).

